### ISSUE TITLE
Create An ISSUE TEMPLATE for this repo!

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#11]
I see other repositories have an issue template for their repository. Create an issue template that can be used when raising issues here.
----
Most of all, be creative <3
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by jfmartinz** [comment]
Just asking if what do you think of this issue template [here](https://github.com/jfmartinz/ResourceHub/blob/main/.github/ISSUE_TEMPLATE/bugreport.yml). If you like it, then I can work on this issue. Please assign it to me. thanks

**Comment by omicreativedev** [comment]
@jfmartinz Yes, that's nice. Nice find. Sure if you would like to give it a go that would be great.

**Comment by jfmartinz** [comment]
> @jfmartinz Yes, that's nice. Nice find. Sure if you would like to give it a go that would be great.

Okay thanks
