### ISSUE TITLE
[Bug] : the logo of the twitter is not updated

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [omicreativedev/hacktoberfest2023#17]
#Description
the logo of the twitter is not updated
Screenshot
<img width="742" alt="Screenshot 2023-10-06 213950" src="https://github.com/omicreativedev/hacktoberfest2023/assets/130988755/b92a04ee-01b6-495d-a659-daa906edf20e">

**Comment by Rohit-Sharmaa** [comment]
@omicreativedev can  assign this issue to me??

**Comment by omicreativedev** [comment]
@Rohit-Sharmaa yes, absolutely. In fact, do you know if there is a logo for X? Would you be open to finding a logo or icon for Linkedin and Dev.to as well?

**Comment by omicreativedev** [comment]
@Rohit-Sharmaa Do you think font-awesome or something similar might give us more options for various social media icons?

**Comment by omicreativedev** [comment]
@Rohit-Sharmaa I found an iconset that has the new X logo already. Have a look:
https://tabler-icons.io/
https://github.com/tabler/tabler-icons
If you haven't started on this, would you be able to integrate this?
