### ISSUE TITLE
Move JavaScript To External Files

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#2]
Currently the JavaScript for the themeswitcher and pagemenu are embeded scripts at the bottom of the index page and the html pages in the pages folder. Migrate the scripts to external files so that people wont accidentally edit them. Keep in mind that the scripts in the html files in the pages folder are slightly different than those in the index.html.

**Comment by shreyanshig** [comment]
Could you please this task to me

**Comment by omicreativedev** [comment]
> Could you please this task to me

Yes, go ahead with it. 
Please read the files in the repo.
Don't forget to add yourself to the CONTRIBUTORS.md file.
Please place the themeswitcher and pageswitcher js in separate files for index.html in the root or in a js folder.
The themeswitcher for all of the pages can go in a js folder in the pages folder.
Compare the code, they are slightly different.
If you know how to make it work better, have a shot at it.
Please make sure when you link the new js files, that you put comments so that we know not to edit.

**Comment by Chetax** [comment]
Can I work on  this

**Comment by omicreativedev** [comment]
@Chetax Yes I assigned you :)

**Comment by Chetax** [comment]
@omicreativedev Can You Please Review  My PR. (Looking For  😊Hactoberfest-accepted)

**Comment by omicreativedev** [comment]
@Chetax I was hoping to do the same for the thankyou.html, omicreativedev.html, etc. But that's fine. We will make a new issue for those.
