### ISSUE TITLE
🐞 [BUG] - Blank Option in Dropdown Box

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#21]
### Issue Verification

- [X] I have verified that this is a new bug report.

### Describe the bug

![oops](https://github.com/omicreativedev/hacktoberfest2023/assets/82254764/e74688aa-868d-4695-8ad6-6f194ef34f5f)
There is a blank box at the bottom of both the page and theme drop down. Clicking them have unintended consequences. 

Clicking the blank one in the page switcher takes you to a 404 in the pages folder.
Clicking the blank one in the theme switcher takes you to no theme.

### Expected behavior

Expected no white box. Expected when clicking that nothing would happen.

### Steps to reproduce

Go to the main website and click either of the drop down boxes. The bottom option in both dropdowns is blank and causing the problem.

### Additional Context

Create a solution for this problem. If it's possible to remove the whitespaces so these options aren't selectable, great. If not possible, perhaps having them redirect back or using a default might be fine.

**Comment by hemanth110702** [comment]
Hey, I would like to work on this. Can you please assign this to me?

**Comment by omicreativedev** [comment]
@hemanth110702  Yes, good luck!

**Comment by hemanth110702** [comment]
Can you please check the pull request. I have done the changes.

**Comment by omicreativedev** [comment]
@hemanth110702 Yes, I will get to it within the day. :) Thank you. Update soon.
