### ISSUE TITLE
Repair Layout For Thank You Contribution Page

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#22]
![omicreativedev-github-io-1200x630desktop-d03057](https://github.com/omicreativedev/hacktoberfest2023/assets/82254764/af756445-6832-47c0-994d-c0ce3e3ea0cf)

Currently the contributor image (which updates dynamically every 24 hours) is falling below the layout. In general, there may be too much space. 
Create a new layout for this page. 
Make sure the logo badge is centered at the top. 
You can make a new theme if you want or use some css within the html file directly as well.
Don't change the metadata.
The theme switcher should work with the page (even if only some elements switch, such as the background.)
Feel free to be creative.
 This page is to thank everyone that contributed to the repository.
 
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Rajiiee** [comment]
Pls give me this issue

**Comment by omicreativedev** [comment]
@Rajiiee You are assigned!

**Comment by Rajiiee** [comment]
@omicreativedev  I've done changes in the galaxy theme .pls accept my pr. iam working on the other two themes as well
