### ISSUE TITLE
Create a Pull Request Template for this repository

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#26]
Please make yourself familiar with the types of issues and pages in this repository.
The pull request template will help identify related issues or other important factors before review.
Research may be neccessary. The final submission should be a working file that applies out the box.
There should be an option for:
Issue Related [] (if so, what issue #)
General Contribution[] (a)page (b)theme (c)debugging (e)enhancement
More information here:
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Starkuser24** [comment]
Please assign it to me.

**Comment by omicreativedev** [comment]
@Starkuser24 you are assigned.

**Comment by Starkuser24** [comment]
Thank you @omicreativedev, I have made the PR accordingly
