### ISSUE TITLE
Design a New Homepage for index.html

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#3]
Index.html is currently very basic. The new index.html should have a clearer explanation of the project so please thoroughly familiarize yourself with the project before taking this issue on. Your update should utilize the themes in the themes folder and look good with all themes. You may edit the themes in the themes folder to add additional features and formatting but keep in mind that the pages in the pages folder will also be using the same themes. So your themes should also be universal to these pages. You may edit the pages in pages folder to make everything work together and not break, but try to preserve the original work on those pages (in the pages folder) without changing the way they look (even if you change some classes, add additional classes, etc.)

**Comment by shreyanshig** [comment]
Hi @omicreativedev, please assign this to me

**Comment by yashwanthvarma18** [comment]
Hey @omicreativedev  please assign me

**Comment by omicreativedev** [comment]
@yashwanthvarma18 
Yes, you may begin.
Please don't edit the javascript for the theme switcher or page switcher.
Since there are not a lot of pages and themes yet, if you add additional classes, update themes with anything universal.
Good luck!

**Comment by Ramiz1336** [comment]
Hi @omicreativedev please assign me

**Comment by omicreativedev** [comment]
@Ramiz1336 You are assigned. Good luck!
