### ISSUE TITLE
Update Social Media Icons In Templates

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#37]
Currently we are using SVG for the social media icons in the templates.

Integrate the cloud version of the following icon library
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@latest/tabler-icons.min.css">
About the library and styling the icons:
- https://tabler-icons.io/
- https://github.com/tabler/tabler-icons

1) Replace the Twitter Icon SVG in omicreativedev.html with the brand-x icon in the icon library
2) Replace the Github SGV with the line icon from the icon library
3) Add linkedin (blank href="#")

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.💗

Be as creative as you want with color, animation, styling, etc.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by Virtual4087** [comment]
assign me

**Comment by omicreativedev** [comment]
@Virtual4087 You are assigned.

**Comment by Virtual4087** [comment]
should i set the target of all the social medias to blank or only LinkedIn?

**Comment by omicreativedev** [comment]
@Virtual4087 You can set them all to blank. :)

**Comment by Virtual4087** [comment]
ok

**Comment by Virtual4087** [comment]
done can you check it and tell me if you want some other changes
