### ISSUE TITLE
Add Confetti Burst on Thank You Page

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#39]
Example Library (pure js)
https://github.com/KonstantinPankratov/JavaScript-Confetti

Your confetti can be ONCLICK on the logo, on page load or both. You don't have to use the library provided. It can be coded right on the thankyou.html page in a script tag. 

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.💗

Be as creative as you want with color, animation, styling, etc.
Read the Docs.
Give a ⭐
Don't break anything. :)

**Comment by gurjott** [comment]
please assign me

**Comment by Khushi-74** [comment]
please assign me i would love to contribute

**Comment by ayush4028** [comment]
Hey @omicreativedev , I have the expertise in this and I think I can solve this. So please assign me this issue

**Comment by ayush4028** [comment]
Hey @omicreativedev, I have done with adding the confetti onclick on the logo and page load both in the thankyou.html page

**Comment by VETREA** [comment]
hello @omicreativedev, can you assign this issue to me 
this will be my first pr

**Comment by Night-Amber3301** [comment]
I've updated the required files and added the feature

Thanks!

**Comment by omicreativedev** [comment]
@Night-Amber3301 You are assigned.

@VETREA @ayush4028 @Khushi-74 @gurjott I will be posting more like this tomorrow if you want to ⭐ for notifications. I am adding a few pages that will need confetti animations by tomorrow.

**Comment by Night-Amber3301** [comment]
Thanks for assigning it to me, looking forward for my PR to get merged, thanks for your time and consideration @omicreativedev
