### ISSUE TITLE
Make an Accessible Color Scheme called Tritan for Tritanopia #wcag #a11y

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#45]
Make an accessible color scheme theme for Tritanopia.
This requires some research about what colors to use for this form of visual impairment.

More information can be found here.
- https://www.a11yproject.com/
- http://colorsafe.co/

How To:
- Make a copy of light.css in the /themes folder and rename it to Tritan
- Include your name at the top in a comment
- Change the colors and styles
- Make sure the theme looks good with all current pages in the /pages folder and index.html
- Update the themes_list.txt in the root folder
- Update the Contributors.md file in the root folder and add your information

**If assigned, please fork immediately.**
Comment within 2 days (at least leave a comment) if you haven't done a PR yet.
Resign yourself if you won't get to it so someone else can.??

Be creative.
Read the Docs.
Give a ?
Don't break anything. :)

**Comment by debuuuu007** [comment]
I would like to contribute in this issue as i know a person with tritanopia faces problem in recognizing blue-yellow color. So i will modify it for them.

**Comment by omicreativedev** [comment]
Thank you @debuuuu007 you have been assigned :)

**Comment by Creperi** [comment]
I added a file.

**Comment by debuuuu007** [comment]
I do not think your PR will be merged as i was the one first assigned this issue.
