### ISSUE TITLE
Create A Logo For The Project 

### ISSUE THREAD

**Issue by omicreativedev** [omicreativedev/hacktoberfest2023#61]
Create a logo for the project with the same color scheme as the banner on the README.md
It should say THEMESWITCHER
You can use Canva or whatever you like
Fork and put the logo in the root folder with the filename logo
This is no-code. You shouldn't put the logo in the code.
Have fun!

**Comment by ezhillragesh** [comment]
Hi @omicreativedev  ,

Is it possible to assign this issue to me? I believe I can help in addressing the problem and working towards a solution. 

Looking forward to your response.

Best regards,
Ezhill Ragesh

**Comment by omicreativedev** [comment]
@ezhillragesh You are assigned. Have fun.
